#!/usr/bin/env python

import sys

if __name__=="__main__":

  servertype = "local"
  server = None

  withgui = True

  for arg in sys.argv[1:]:
    arg = arg.lower()
    if arg == '--nogui':
      withgui = False
    else:
      servertype = arg
      break

  if servertype not in ("thrift", "pyro", "local"):
    print "USAGE: AutomatonServer.py [--nogui] [thrift|pyro]"
    sys.exit()

  if servertype == "local" and not withgui:
    print "If local, must have GUI enabled."
    sys.exit()

  if servertype == "local":
    from Automaton.lib.AutomatonServer import AutomatonServer
    server = AutomatonServer(withgui=withgui)
  elif servertype == "thrift":
    try:
      from Automaton.lib.AutomatonServer_thrift import ThriftServer
      server = ThriftServer(withgui=withgui)
    except ImportError:
      servertype = "pyro"

  # Not elseif so that we can fallthrough if thrift fails
  if servertype == "pyro":
    try:
      from Automaton.lib.AutomatonServer_pyro import PyroServer
      server = PyroServer(withgui=withgui)
    except ImportError:
      pass

  if server==None:
    print "Error: Specified server type not installed."
    sys.exit()

  server.initialize()

  print 'Starting the server...'
  try:
    server.start()
  except KeyboardInterrupt:
    pass

