#!/usr/bin/env python

import sys

if __name__=="__main__":

  servertype = "local"
  server = None

  withgui = True

  for arg in sys.argv[1:]:
    arg = arg.lower()
    if arg == '--nogui':
      withgui = False
    else:
      servertype = arg
      break

  if servertype not in ("cherry", "bottle", "thrift", "pyro", "local"):
    print "USAGE: AutomatonServer [--nogui] [cherry|bottle|thrift|pyro]"
    sys.exit()

  if servertype == "local" and not withgui:
    print "If local, must have GUI enabled."
    sys.exit()

  if servertype == "local":
    from automaton.server.base import AutomatonServer
    server = AutomatonServer(withgui=withgui)
    
  if servertype == "cherry":
    #try:
    from automaton.server.cherry import CherryServer
    server = CherryServer(withgui=withgui)
    print "Using CherryPy"
#    except ImportError as err:
#      print "CherryPy failed to import - falling back to Thrift:", err
#      servertype = "thrift"

#  if servertype == "bottle":
#    try:
#      from automaton.server.bottle import BottleServer
#      server = BottleServer(withgui=withgui)
#      print "Using Bottle"
#    except ImportError as err:
#      print "Bottle failed to import - falling back to Thrift:", err
#      servertype = "thrift"

  # Not elseif so that we can fallthrough if bottle fails
  if servertype == "thrift":
    try:
      from automaton.server.thrift import ThriftServer
      server = ThriftServer(withgui=withgui)
      print "Using thrift"
    except ImportError as err:
      print "Thrift failed to import - falling back to pyro:", err
      servertype = "pyro"

  if servertype == "pyro":
    try:
      from automaton.server.pyro import PyroServer
      server = PyroServer(withgui=withgui)
      print "Using Pyro"
    except ImportError:
      pass

  if server==None:
    print "Error: Specified server type not installed."
    sys.exit()

  # The local server has no initialization
  if hasattr(server, "initialize"):
    server.initialize()

  print 'Starting the server...'
  try:
    server.start()
  except KeyboardInterrupt:
    print "Keyboard Interrupt caught, exiting..."

