#!/bin/sh
#
# Start Automaton Server
#

EXECPATH=/home/dan/prg/py/Automaton

case "$1" in
   'start')
      $EXECPATH/AutomatonServer & ;;
   'stop')
      for process in $(pgrep -f AutomatonServer)
        do kill $process
      done ;;
   'restart')
      for process in $(pgrep -f AutomatonServer);
        do kill $process
      done
      sleep 5
      $EXECPATH/AutomatonServer & ;;
   *)
      echo "usage $0 start|stop|restart" ;;
esac

